import type { Metadata } from "next";
import "./globals.css";
import { TimerProvider } from '../context/TimerContext';
import { TextProvider } from '../context/TextContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TimerProvider>
    <TextProvider>
    <html lang="en">
      <body className="min-h-screen">{children}</body>
    </html>
    </TextProvider>
    </TimerProvider>
  );
}
