import type { Metadata } from "next";
import "./globals.css";
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
import { TimerProvider } from "@/contexts/TimerContext";
import { TextProvider } from "@/contexts/TextContext";
import Footer from "@/components/Footer";
import { I18nextProvider } from 'react-i18next';
import { ModelLoadedProvider } from '@/contexts/ModelLoadedContext';
import { Analytics } from "@vercel/analytics/react"
// import i18n from '../i18n';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <I18nextProvider i18n={i18n}>
    <ModelLoadedProvider>
    <TimerProvider>
    <TextProvider>
    <html lang="en">
      <body className="min-h-screen">
      <Analytics/>
        {children}
        <Footer/>
        </body>
    </html>
    </TextProvider>
    </TimerProvider>
    </ModelLoadedProvider>
    //  </I18nextProvider>
  );
}
